// CodeMirror, copyright (c) by Marijn Haverbeke and others
// Distributed under an MIT license: https://codemirror.net/LICENSE

(function(mod) {
  'use strict';
  if (typeof exports == 'object' && typeof module == 'object') // CommonJS
    mod(require('../../lib/codemirror'));
  else if (typeof define == 'function' && define.amd) // AMD
    define(['../../lib/codemirror'], mod);
  else // Plain browser env
    mod(window.CodeMirror);
})(function(CodeMirror) {
'use strict';

CodeMirror.defineMode('tesscript', function() {
  function buildRegexp(patterns, options) {
    options = options || {};
    var prefix = options.prefix !== undefined ? options.prefix : '^';
    var suffix = options.suffix !== undefined ? options.suffix : '\\b';

    for (var i = 0; i < patterns.length; i++) {
      if (patterns[i] instanceof RegExp) {
        patterns[i] = patterns[i].source;
      }
      else {
        patterns[i] = patterns[i].replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
      }
    }

    return new RegExp(prefix + '(' + patterns.join('|') + ')' + suffix, 'i');
  }

  var notCharacterOrDash = '(?=[^A-Za-z\\d\\-_]|$)';
    
  var varNames = /[\w\-:]/
  
  var keywords = buildRegexp([
    /begin|continue|if|else|elseif|end|endif|for|foreach|return|where|while|ScriptName|scn|Loop|Goto|Label|saveIP|RestoreIP/
  ], { suffix: notCharacterOrDash });

  var punctuation = /[\[\]{},\.]|@[({]/;
    
  var wordOperators = buildRegexp([
    /set|let|to/
  ], { prefix: '' });
    
  var symbolOperators = /[+\-*\/%]=|\+\+|--|\.\.|[+\-*&^%:=!|\/]|<(?!#)|(?!#)>/;
    
  var operators = buildRegexp([wordOperators, symbolOperators], { suffix: '' });

  var numbers = /^((0x[\da-f]+)|((\d+\.\d+|\d\.|\.\d+|\d+)(e[\+\-]?\d+)?))[ld]?([kmgtp]b)?/i;

  var identifiers = /^[A-Za-z\_][A-Za-z\-\_\d]*\b/;

  var symbolBuiltins = /[A-Z]:|%|\?/i;
    
  var varBuiltins = buildRegexp([
    /short|float|ref|string_var|array_var|long/
  ], { prefix: '', suffix: '' });
    
  var vanillaBuiltins = buildRegexp([
    /Activate|AddAchievement|AddFlames|AddItem|AddScriptPackage|AddSpell|AddTopic|AdvancePCLevel|AdvancePCSkill|Autosave|CanHaveFlames|CanPayCrimeGold|Cast|ClearOwnership|CloseCurrentOblivionGate|CloseOblivionGate|CompleteQuest|CreateFullActorCopy|DeleteFullActorCopy|Disable|DisableLinkedPathPoints|DisablePlayerControls|Dispel|DispelAllSpells|Drop|DropMe|DuplicateAllItems|DuplicateNPCStats|Enable|EnableFastTravel|EnableLinkedPathPoints|EnablePlayerControls|EquipItem|EssentialDeathReload|EvaluatePackage|ForceActorValue|ForceAV|ForceCloseOblivionGate|ForceFlee|ForceTakeCover|ForceWeather|GetActionRef|GetActorValue|GetAV|GetAlarmed|GetAmountSoldStolen|GetAngle|GetArmorRating|GetArmorRatingUpperBody|GetAttacked|GetBarterGold|GetBaseActorValue|GetBaseAV|GetButtonPressed|GetClassDefaultMatch|GetClothingValue|GetCombatTarget|GetContainer|GetCrime|GetCrimeGold|GetCrimeKnown|GetCurrentAIPackage|GetCurrentAIProcedure|GetCurrentTime|GetCurrentWeatherPercent|GetDayOfWeek|GetDead|GetDeadCount|GetDestroyed|GetDetected|GetDetectionLevel|GetDisabled|GetDisposition|GetDistance|GetDoorDefaultOpen|GetEquipped|GetFactionRank|GetFactionRankDifference|GetFactionReaction|GetFatiguePercentage|GetForceRun|GetForceSneak|GetFriendHit|GetFurnitureMarkerID|GetGameSetting|GetGlobalValue|GetGold|GetHeadingAngle|GetIdleDoneOnce|GetIgnoreFriendlyHits|GetInCell|GetInCellParam|GetInFaction|GetInSameCell|GetInvestmentGold|GetInWorldspace|GetIsAlerted|GetIsClass|GetIsClassDefault|GetIsCreature|GetIsCurrentPackage|GetIsCurrentWeather|GetIsGhost|GetIsID|GetIsPlayableRace|GetIsPlayerBirthsign|GetIsRace|GetIsReference|GetIsSex|GetIsUsedItem|GetIsUsedItemType|GetItemCount|GetKnockedState|GetLevel|GetLocked|GetLockLevel|GetLOS|GetNoRumors|GetOffersServicesNow|GetOpenState|GetPackageTarget|GetParentRef|GetPCExpelled|GetPCFactionAttack|GetPCFactionMurder|GetPCFactionSteal|GetPCFactionSubmitAuthority|GetPCFame|GetPCInFaction|GetPCInfamy|GetPCIsClass|GetPCIsRace|GetPCIsSex|GetPCMiscStat|GetPCSleepHours|GetPersuasionNumber|GetPlayerControlsDisabled|GetPlayerHasLastRiddenHorse|GetPlayerInSEWorld|GetPos|GetQuestRunning|GetQuestVariable|GetRandomPercent|GetRestrained|GetScale|GetScriptVariable|GetSecondsPassed|GetSelf|GetShouldAttack|GetSitting|GetSleeping|GetStage|GetStageDone|GetStartingAngle|GetStartingPos|GetTalkedToPC|GetTalkedToPCParam|GetTimeDead|GetTotalPersuasionNumber|GetTrespassWarningLevel|GetUnconscious|GetUsedItemActivate|GetUsedItemLevel|GetVampire|GetWalkSpeed|GetWeaponAnimType|GetWeaponSkillType|GetWindSpeed|GoToJail|HasFlames|HasMagicEffect|HasVampireFed|IsActionRef|IsActor|IsActorAVictim|IsActorDetected|IsActorEvil|IsActorsAIOff|IsActorUsingATorch|IsAnimPlaying|IsCellOwner|IsCloudy|IsContinuingPackagePCNear|IsCurrentFurnitureObj|IsCurrentFurnitureRef|IsEssential|IsFacingUp|IsGuard|IsHorseStolen|IsIdlePlaying|IsInCombat|IsInDangerousWater|IsInInterior|IsInMyOwnedCell|IsLeftUp|IsOwner|IsPCAMurderer|IsPCSleeping|IsPlayerInJail|IsPlayerMovingIntoNewSpace|IsPlayersLastRiddenHorse|IsPleasant|IsRaining|IsRidingHorse|IsRunning|IsShieldOut|IsSneaking|IsSnowing|IsSpellTarget|IsSwimming|IsTalking|IsTimePassing|IsTorchOut|IsTrespassing|IsTurnArrest|IsWaiting|IsWeaponOut|IsXBox|IsYielding|Kill|KillAllActors|Lock|Look|LoopGroup|Message|MessageBox|ModActorValue|ModAV|ModAmountSoldStolen|ModBarterGold|ModCrimeGold|ModDisposition|ModFactionRank|ModFactionReaction|ModPCAttribute|ModPCFame|ModPCInfamy|ModPCMiscStat|ModPCSkill|ModScale|MoveTo|PayFine|PayFineThief|PickIdle|PlaceAtMe|PlayBink|PlayGroup|PlayMagicEffectVisuals|PlayMagicShaderVisuals|PlaySound|PlaySound3D|PositionCell|PositionWorld|PreloadMagicEffect|PurgeCellBuffers|PCB|PushActorAway|RefreshTopicList|ReleaseWeatherOverride|RemoveAllItems|RemoveFlames|RemoveItem|RemoveMe|RemoveScriptPackage|RemoveSpell|Reset3DState|ResetFallDamageTimer|ResetHealth|ResetInterior|Resurrect|Rotate|SameFaction|SameFactionAsPC|SameRace|SameRaceAsPC|SameSex|SameSexAsPC|Say|SayTo|ScriptEffectElapsedSeconds|SelectPlayerSpell|SendTrespassAlarm|SetActorAlpha|SetActorFullName|SetActorRefraction|SetActorsAI|SetActorValue|SetAV|SetAlert|SetAllReachable|SetAllVisible|SetAngle|SetBarterGold|SetCellFullName|SetCellOwnership|SetCellPublicFlag|SetClass|SetCombatStyle|SetCrimeGold|SetDestroyed|SetDoorDefaultOpen|SetEssential|SetFactionRank|SetFactionReaction|SetForceRun|SetForceSneak|SetGhost|SetIgnoreFriendlyHits|SetInCharGen|SetInvestmentGold|SetItemValue|SetLevel|SetNoAvoidance|SetNoRumors|SetOpenState|SetOwnership|SetPackDuration|SetPCExpelled|SetPCFactionAttack|SetPCFactionMurder|SetPCFactionSteal|SetPCFactionSubmitAuthority|SetPCFame|SetPCInfamy|SetPCSleepHours|SetPlayerInSEWorld|SetPos|SetQuestObject|SetRestrained|SetRigidBodyMass|SetScale|SetSceneIsComplex|SetShowQuestItems|SetSize|SetStage|SetUnconscious|SetWeather|ShowBirthsignMenu|ShowClassMenu|ShowDialogSubtitles|ShowEnchantment|ShowMap|ShowRaceMenu|ShowSpellMaking|SkipAnim|StartCombat|StartConversation|StartQuest|StopCombat|StopCombatAlarmOnActor|SCAOnActor|StopLook|StopMagicEffectVisuals|StopMagicShaderVisuals|StopQuest|StopWaiting|StreamMusic|This|ToggleActorsAI|TrapUpdate|TriggerHitShader|UnequipItem|Unlock|VampireFeed|Wait|WakeUpPC|WhichServiceMenu|Yield/
  ], { prefix: '', suffix: '' });
    
  var obseBuiltins = buildRegexp([ 
      /Abs|ACos|dacos|racos|Activate2|ActorValueToCode|ActorValueToString|AVString|ActorValueToStringC|AddEffectItem|AddEffectItemC|AddEffectItemC|AddFullEffectItem|AddFullEffectItemC|AddItemNS|AddMagicEffectCounter|AddMagicEffectCounterC|AddSpellNS|AddToLeveledList|AHammerKey|Algohol|AnimPathIncludes|AppendToName|Ar_Append|Ar_BadNumericIndex|Ar_BadStringIndex|Ar_Construct|Ar_Copy|Ar_CustomSort|Ar_DeepCopy|Ar_Dump|Ar_DumpID|Ar_Erase|Ar_Find|Ar_First|Ar_HasKey|Ar_Insert|Ar_InsertRange|Ar_Keys|Ar_Last|Ar_List|Ar_Map|Ar_Next|Ar_Null|Ar_Prev|Ar_Range|Ar_Resize|Ar_Size|Ar_Sort|Ar_SortAlpha|AsciiToChar|ASin|dasin|rasin|ATan|datan|ratan|ATan2|datan2|ratan2|CalcLeveledItem|CalcLevItemNR|CalcLevItems|Call|CanCastPower|CanCorpseCheck|CanFastTravelFromWorld|CanTravelToMapMarker|Ceil|CharToASCII|ClearActiveQuest|ClearHotkey|ClearLeveledList|ClearOwnershipT|ClearPlayersLastRiddenHorse|ClickMenuButton|CloneForm|CloseAllMenus|CloseTextInput|CompareFemaleBipedPath|CompareFemaleGroundPath|CompareFemaleIconPath|CompareIconPath|IconPathIncludes|CompareMaleBipedPath|CompareMaleGroundPath|CompareMaleIconPath|CompareModelPath|ModelPathIncludes|CompareName|CompareNames|CompareScripts|Con_CAL|Con_GetINISetting|Con_HairTint|Con_LoadGame|Con_ModWaterShader|Con_PlayerSpellBook|Con_QuitGame|Con_RefreshINI|Con_RunMemoryPass|Con_Save|Con_SaveINI|Con_SetCameraFOV|Con_SetClipDist|Con_SetFog|Con_SetGameSetting|Con_SetGamma|Con_SetHDRParam|Con_SetImageSpaceGlow|Con_SetINISetting|Con_SetSkyParam|Con_SetTargetRefraction|Con_SetTargetRefractionFire|Con_SexChange|Con_TCL|Con_TFC|Con_TGM|Con_ToggleAI|Con_ToggleCombatAI|Con_ToggleDetection|Con_ToggleMapMarkers|Con_ToggleMenus|Con_WaterDeepColor|Con_WaterReflectionColor|Con_WaterShallowColor|CopyAllEffectItems|CopyEyes|CopyFemaleBipedPath|CopyFemaleGroundPath|CopyFemaleIconPath|CopyHair|CopyIconPath|CopyIR|CopyMaleBipedPath|CopyMaleGroundPath|CopyMaleIconPath|CopyModelPath|CopyName|CopyNthEffectItem|Cos|dcos|rcos|Cosh|dcosh|rcosh|CreateTempRef|CreatureHasNoHead|CreatureHasNoLeftArm|CreatureHasNoMovement|CreatureHasNoRightArm|CreatureNoCombatInWater|CreatureUsesWeaponAndShield|DebugPrint|DeleteFromInputText|DeleteReference|DisableControl|DisableKey|DisableMouse|DispelNthActiveEffect|DispelNthAE|EnableControl|EnableKey|EnableMouse|EquipItem2|EquipItem2NS|EquipItemNS|EquipItemSilent|EquipMe|Exp|FactionHasSpecialCombat|FileExists|Floor|Fmod|ForceColumnVector|ColVec|ForceRowVector|RowVec|GenerateIdentityMatrix|IdentityMat|GenerateRotationMatrix|RotMat|GenerateZeroMatrix|ZeroMat|GetActiveEffectCasters|GetActiveEffectCodes|GetActiveEffectCount|GetActiveMenuFilter|GetActiveMenuMode|GetActiveMenuObject|GetActiveMenuRef|GetActiveMenuSelection|GetActiveQuest|GetActiveUIComponentFullName|GetActiveUIComponentID|GetActiveUIComponentName|GetActorAlpha|GetActorBaseLevel|GetActorLightAmount|GetActorMaxLevel|GetMaxLevel|GetActorMinLevel|GetMinLevel|GetActorPackages|GetActorSoulLevel|GetActorValueC|GetAVC|GetAlchMenuApparatus|GetAlchMenuIngredient|GetAlchMenuIngredientCount|GetAllies|GetAllModLocalData|GetAltControl|GetAltControl2|GetApparatusType|GetArmorAR|GetArmorType|GetArrayVariable|GetArrowProjectileBowEnchantment|GetAPBowEnch|GetArrowProjectileEnchantment|GetAPEnch|GetArrowProjectilePoison|GetAPPoison|GetAttackDamage|GetAVForBaseActor|GetAVForBaseActorC|GetAVMod|GetAVModC|GetBarterItem|GetBarterItemQuantity|GetBaseActorValueC|GetBaseAV2|GetBaseAV2C|GetBaseItems|GetBaseObject|GetBipedIconPath|GetBipedModelPath|GetBipedSlotMask|GetBirthsignSpells|GetBookCantBeTaken|GetBookIsScroll|GetBookLength|GetBookSkillTaught|GetBookText|GetBoundingBox|GetBoundingRadius|GetCalcAllLevels|GetCalcEachInCount|GetCallingScript|GetCellBehavesAsExterior|GetCellChanged|GetCellClimate|GetCellDetachTime|GetCellLighting|GetCellMusicType|GetCellNorthRotation|GetCellResetHours|GetCellWaterType|GetChanceNone|GetClass|GetClassAttribute|GetClassMenuHighlightedClass|GetClassMenuSelectedClass|GetClassSkill|GetClassSkills|GetClassSpecialization|GetClimateHasMasser|GetClimateHasSecunda|GetClimateMoonPhaseLength|GetClimateSunriseBegin|GetClimateSunriseEnd|GetClimateSunsetBegin|GetClimateSunsetEnd|GetClimateVolatility|GetCloseSound|GetCombatSpells|GetCombatStyle|GetCombatStyleAcrobaticsDodgeChance|GetCombatStyleAttackChance|GetCombatStyleAttackDuringBlockMult|GetCombatStyleAttackNotUnderAttackMult|GetCombatStyleAttackSkillModBase|GetCombatStyleAttackSkillModMult|GetCombatStyleAttackUnderAttackMult|GetCombatStyleBlockChance|GetCombatStyleBlockNotUnderAttackMult|GetCombatStyleBlockSkillModBase|GetCombatStyleBlockSkillModMult|GetCombatStyleBlockUnderAttackMult|GetCombatStyleBuffStandoffDist|GetCombatStyleDodgeBackNotUnderAttackMult|GetCombatStyleDodgeBackTimerMax|GetCombatStyleDodgeBackTimerMin|GetCombatStyleDodgeBackUnderAttackMult|GetCombatStyleDodgeChance|GetCombatStyleDodgeFatigueModBase|GetCombatStyleDodgeFatigueModMult|GetCombatStyleDodgeFWAttackingMult|GetCombatStyleDodgeFWNotAttackingMult|GetCombatStyleDodgeFWTimerMax|GetCombatStyleDodgeFWTimerMin|GetCombatStyleDodgeLRChance|GetCombatStyleDodgeLRTimerMax|GetCombatStyleDodgeLRTimerMin|GetCombatStyleDodgeNotUnderAttackMult|GetCombatStyleDodgeUnderAttackMult|GetCombatStyleEncumberedSpeedModBase|GetCombatStyleEncumberedSpeedModMult|GetCombatStyleFleeingDisabled|GetCombatStyleGroupStandoffDist|GetCombatStyleH2HBonusToAttack|GetCombatStyleHoldTimerMax|GetCombatStyleHoldTimerMin|GetCombatStyleIdleTimerMax|GetCombatStyleIdleTimerMin|GetCombatStyleIgnoreAlliesInArea|GetCombatStyleKOBonusToAttack|GetCombatStyleKOBonusToPowerAttack|GetCombatStyleMeleeAlertOK|GetCombatStylePowerAttackChance|GetCombatStylePowerAttackFatigueModBase|GetCombatStylePowerAttackFatigueModMult|GetCombatStylePrefersRanged|GetCombatStyleRangedStandoffDist|GetCombatStyleRangeMaxMult|GetCombatStyleRangeOptimalMult|GetCombatStyleRejectsYields|GetCombatStyleRushAttackChance|GetCombatStyleRushAttackDistMult|GetCombatStyleStaggerBonusToAttack|GetCombatStyleStaggerBonusToPowerAttack|GetCombatStyleSwitchDistMelee|GetCombatStyleSwitchDistRanged|GetCombatStyleWillYield|GetCompletedQuests|GetContainerMenuView|GetContainerRespawns|IsUnsafeRespawns|GetControl|GetCreatureBaseScale|GetCreatureCombatSkill|GetCreatureFlies|GetCreatureMagicSkill|GetCreatureModelPaths|GetCreatureReach|GetCreatureSoulLevel|GetCreatureSound|GetCreatureSoundBase|GetCreatureStealthSkill|GetCreatureSwims|GetCreatureType|GetCreatureWalks|GetCrosshairRef|GetCurrentCharge|GetCurrentClimateID|GetCurrentEditorPackage|GetCurrentEventName|GetCurrentHealth|GetCurrentPackage|GetCurrentPackageProcedure|GetCurrentQuests|GetCurrentRegion|GetCurrentRegions|GetCurrentScript|GetCurrentSoulLevel|GetCurrentWeatherID|GetCursorPos|GetDebugSelection|GetDescription|GetDoorTeleportRot|GetDoorTeleportX|GetDoorTeleportY|GetDoorTeleportZ|GetEditorID|GetEditorSize|GetEnchantment|GetEnchantmentCharge|GetEnchantmentCost|GetEnchantmentType|GetEnchMenuBaseItem|GetEnchMenuEnchItem|GetEnchMenuSoulgem|GetEquipmentSlot|GetEquipmentSlotMask|GetEquippedCurrentCharge|GetEquippedCurrentHealth|GetEquippedItems|GetEquippedObject|GetEquippedTorchTimeLeft|GetEquippedWeaponPoison|GetEyes|GetFallTimer|GetFirstRef|GetFirstRefInCell|GetFollowers|GetFormFromMod|GetFormIDString|GetFPS|GetFullGoldValue|GetGameDifficulty|GetGameLoaded|GetGameRestarted|GetGodMode|GetGoldValue|GetGridsToLoad|GetHair|GetHairColor|GetHidesAmulet|GetHidesRings|GetHorse|GetHotkeyItem|GetIconPath|GetIgnoresResistance|GetIngredient|GetIngredientChance|GetInputText|GetInventoryObject|GetInvRefsForItem|GetItems|GetKeyName|GetKeyPress|GetLastCreatedPotion|GetLastCreatedSpell|GetLastEnchantedItem|GetLastSigilStoneCreatedItem|GetLastSigilStoneEnchantedItem|GetLastTransactionItem|GetLastTransactionQuantity|GetLastUniqueCreatedPotion|GetLastUsedSigilStone|GetLeveledSpells|GetLevItemByLevel|GetLevItemIndexByForm|GetLevItemIndexByLevel|GetLightDuration|GetLightRadius|GetLightRGB|GetLinkedDoor|GetLocalGravity|GetLoopSound|GetLuckModifiedSkill|GetMagicEffectAreaSound|GetMagicEffectAreaSoundC|GetMagicEffectBarterFactor|GetMEEBarter|GetMagicEffectBarterFactorC|GetMEEBarterC|GetMagicEffectBaseCost|GetMEBaseCost|GetMagicEffectBaseCostC|GetMEBaseCostC|GetMagicEffectBoltSound|GetMagicEffectBoltSoundC|GetMagicEffectCastingSound|GetMagicEffectCastingSoundC|GetMagicEffectChars|GetMagicEffectCharsC|GetMagicEffectCode|GetMagicEffectCounters|GetMagicEffectCountersC|GetMagicEffectEnchantFactor|GetMEEnchant|GetMagicEffectEnchantFactorC|GetMEEnchantC|GetMagicEffectEnchantShader|GetMagicEffectEnchantShaderC|GetMagicEffectHitShader|GetMagicEffectHitShaderC|GetMagicEffectHitSound|GetMagicEffectHitSoundC|GetMagicEffectIcon|GetMagicEffectIconC|GetMagicEffectLight|GetMagicEffectLightC|GetMagicEffectModel|GetMagicEffectModelC|GetMagicEffectName|GetMagicEffectNameC|GetMagicEffectNumCounters|GetMagicEffectNumCountersC|GetMagicEffectOtherActorValue|GetMagicEffectOtherActorValueC|GetMEOtherActorValue|GetMEOtherActorValueC|GetMagicEffectProjectileSpeed|GetMEProjSpeed|GetMagicEffectProjectileSpeedC|GetMEProjSpeedC|GetMagicEffectResistValue|GetMagicEffectResistValueC|GetMagicEffectSchool|GetMESchool|GetMagicEffectSchoolC|GetMESchoolC|GetMagicEffectUsedObject|GetMagicEffectUsedObjectC|GetMEUsedObject|GetMEUsedObject|GetMagicItemEffectCount|GetMIEffectCount|GetMagicItemType|GetMIType|GetMagicProjectileSpell|GetMPSpell|GetMapMarkers|GetMapMarkerType|GetMapMenuMarkerName|GetMapMenuMarkerRef|GetMaxAV|GetMaxAVC|GetMenuFloatValue|GetMenuHasTrait|GetMenuStringValue|GetMerchantContainer|GetMessageBoxType|GetMiddleHighActors|GetModelPath|GetModIndex|GetModLocalData|GetMouseButtonPress|GetMouseButtonsSwapped|GetName|GetNextRef|GetNthActiveEffectActorValue|GetNthAEAV|GetNthActiveEffectBoundItem|GetNthAEBoundItem|GetNthActiveEffectCaster|GetNthAECaster|GetNthActiveEffectCode|GetNthAECode|GetNthActiveEffectData|GetNthAEData|GetNthActiveEffectDuration|GetNthAEDuration|GetNthActiveEffectEnchantObject|GetNthActiveEffectMagicEnchantObject|GetNthAEMagicEnchantObject|GetNthActiveEffectMagicItem|GetNthAEMagicItem|GetNthActiveEffectMagicItemIndex|GetNthAEIndex|GetNthActiveEffectMagnitude|GetNthAEMagnitude|GetNthActiveEffectSummonRef|GetNthAESummonRef|GetNthActiveEffectTimeElapsed|GetNthAETime|GetNthChildRef|GetNthDetectedActor|GetNthEffectItem|GetNthEffectItemActorValue|GetNthEIAV|GetNthEffectItemArea|GetNthEIArea|GetNthEffectItemCode|GetNthEICode|GetNthEffectItemDuration|GetNthEIDuration|GetNthEffectItemMagnitude|GetNthEIMagnitude|GetNthEffectItemName|GetNthEIName|GetNthEffectItemRange|GetNthEIRange|GetNthEffectItemScript|GetNthEIScript|GetNthEffectItemScriptName|GetNthEffectItemScriptSchool|GetNthEISSchool|GetNthEffectItemScriptVisualEffect|GetNthEISVisualEffect|GetNthExplicitRef|GetNthFaction|GetNthFactionRankName|GetNthFollower|GetNthLevItem|GetNthLevItemCount|GetNthLevItemLevel|GetNthMagicEffectCounter|GetNthMagicEffectCounterC|GetNthModName|GetNthPackage|GetNthPlayerSpell|GetNthRaceBonusSkill|GetNthRaceSpell|GetNthSpell|GetNumChildRefs|GetNumDetectedActors|GetNumericINISetting|GetNumExplicitRefs|GetNumFactions|GetNumFollowers|GetNumItems|GetNumKeysPressed|GetNumLevItems|GetNumLoadedPlugins|GetNumMouseButtonsPressed|GetNumPackages|GetNumRanks|GetNumRefs|GetNumRefsInCell|GetHighActors|GetMiddleHighActors|GetLowActors|GetObjectCharge|GetObjectHealth|GetObjectType|GetOblivionDirectory|GetOBSERevision|GetOBSEVersion|GetOpenKey|GetOpenSound|GetOwner|GetOwningFactionRequiredRank|GetPackageAllowFalls|GetPackageAllowSwimming|GetPackageAlwaysRun|GetPackageAlwaysSneak|GetPackageArmorUnequipped|GetPackageContinueIfPCNear|GetPackageData|GetPackageDefensiveCombat|GetPackageLocationData|GetPackageLockDoorsAtEnd|GetPackageLockDoorsAtLocation|GetPackageLockDoorsAtStart|GetPackageMustComplete|GetPackageMustReachLocation|GetPackageNoIdleAnims|GetPackageOffersServices|GetPackageOncePerDay|GetPackageScheduleData|GetPackageSkipFalloutBehavior|GetPackageTargetData|GetPackageUnlockDoorsAtEnd|GetPackageUnlockDoorsAtLocation|GetPackageUnlockDoorsAtStart|GetPackageUseHorse|GetPackageWeaponsUnequipped|GetParentCell|GetParentCellOwner|GetParentCellOwningFactionRequiredRank|GetCellFactionRank|GetParentCellWaterHeight|GetWaterHeight|GetParentWorldspace|GetPathNodeLinkedRef|GetPathNodePos|GetPathNodesInRadius|GetPathNodesInRect|GetPCAttributeBonus|GetPCAttributeBonusC|GetPCLastDroppedItem|GetPCLastDroppedItemRef|GetPCMajorSkillUps|GetPCMovementSpeedModifier|GetPCSpellEffectivenessModifier|GetPCTrainingSessionsUsed|GetPlayerBirthsign|GetPlayerSkillAdvances|GetPlayerSkillAdvancesC|GetPlayerSkillUse|GetPlayersLastActivatedLoadDoor|GetPCLastLoadDoor|GetPlayersLastRiddenHorse|GetPCLastHorse|GetPlayerSpell|GetPlayerSpellCount|GetPluginVersion|GetProcessLevel|GetProjectile|GetProjectileDistanceTraveled|GetProjectileLifetime|GetProjectileSource|GetProjectileSpeed|GetProjectileType|GetQuality|GetQuantityMenuCurrentQuantity|GetQuantityMenuItem|GetQuantityMenuMaximumQuantity|GetRace|GetRaceAttribute|GetRaceAttributeC|GetRaceDefaultHair|GetRaceEyes|GetRaceHairs|GetRaceReaction|GetRaceScale|GetRaceSkillBonus|GetRaceSkillBonusC|GetRaceSpellCount|GetRaceVoice|GetRaceWeight|GetRawFormIDString|GetRefCount|GetRefVariable|GetRequiredSkillExp|GetRider|GetRuntimeEditorID|GetScript|GetScriptActiveEffectIndex|GetSelectedSpells|GetServicesMask|GetSigilStoneUses|GetSkillGoverningAttribute|GetSkillSpecialization|GetSkillUseIncrement|GetSkillUseIncrementC|GetSoulGemCapacity|GetSoulLevel|GetSoundPlaying|GetSourceModIndex|GetSpecialAnims|GetSpellAreaEffectIgnoresLOS|GetSpellCount|GetSpellDisallowAbsorbReflect|GetSpellEffectiveness|GetSpellExplodesWithNoTarget|GetSpellImmuneToSilence|GetSpellMagickaCost|GetSpellMasteryLevel|GetSpellPCStart|GetSpells|GetSpellSchool|GetSpellScriptEffectAlwaysApplies|GetSpellType|GetStringGameSetting|GetStringINISetting|GetTargets|GetTelekinesisRef|GetTeleportCell|GetTeleportCellName|GetTerrainHeight|GetTextInputControlPressed|GetTextInputCursorPos|GetTexturePath|GetTileChildren|GetTileTraits|GetTimeLeft|GetTotalActiveEffectMagnitude|GetTotalAEMagnitude|GetTotalActiveEffectMagnitudeC|GetTotalAEMagnitudeC|GetTotalAEAbilityMagnitude|GetTotalAEAbilityMagnitudeC|GetTotalAEAlchemyMagnitude|GetTotalAEAlchemyMagnitudeC|GetTotalAEAllSpellsMagnitude|GetTotalAEAllSpellsMagnitudeC|GetTotalAEDiseaseMagnitude|GetTotalAEDiseaseMagnitudeC|GetTotalAEEnchantmentMagnitude|GetTotalAEEnchantmentMagnitudeC|GetTotalAELesserPowerMagnitude|GetTotalAELesserPowerMagnitudeC|GetTotalAENonAbilityMagnitude|GetTotalAENonAbilityMagnitudeC|GetTotalAEPowerMagnitude|GetTotalAEPowerMagnitudeC|GetTotalAESpellMagnitude|GetTotalAESpellMagnitudeC|GetTotalPCAttributeBonus|GetTrainerLevel|GetTrainerSkill|GetTransactionInfo|GetTravelHorse|GetUsedPowers|GetUserTime|GetVariable|GetVelocity|GetVerticalVelocity|GetWaterShader|GetWeaponReach|GetWeaponSpeed|GetWeaponType|GetWeatherClassification|GetWeatherCloudSpeedLower|GetCloudSpeedLower|GetWeatherCloudSpeedUpper|GetCloudSpeedUpper|GetWeatherColor|GetWeatherFogDayFar|GetFogDayFar|GetWeatherFogDayNear|GetFogDayNear|GetWeatherFogNightFar|GetFogNightFar|GetWeatherFogNightNear|GetFogNightNear|GetWeatherHDRValue|GetHDRValue|GetWeatherLightningFrequency|GetLightningFrequency|GetWeatherOverride|GetWeatherSunDamage|GetSunDamage|GetWeatherSunGlare|GetSunGlare|GetWeatherTransDelta|GetTransDelta|GetWeatherWindSpeed|GetWindSpeed|GetWeight|GetWorldSpaceParentWorldSpace|GetWorldParentWorld|GlobalVariableExists|HammerKey|HasBeenPickedUp|HasEffectShader|HasLowLevelProcessing|HasModel|HasName|HasNoPersuasion|HasSpell|HasTail|HasVariable|HoldKey|IncrementPlayerSkillUse|InsertInInputText|IsActivatable|IsActivator|IsActorRespawning|IsAlchemyItem|IsPotion|IsAmmo|IsAnimGroupPlaying|IsApparatus|IsArmor|IsAttacking|IsAutomaticDoor|IsBarterMenuActive|IsBipedIconPathValid|IsBipedModelPathValid|IsBlocking|IsBook|IsCasting|IsCellPublic|IsClassAttribute|IsClassSkill|IsMajor|IsClassSkillC|IsMajorC|IsClonedForm|IsClothing|IsConsoleOpen|IsContainer|IsControl|IsControlDisabled|IsControlPressed|IsCreature|IsCreatureBiped|IsDigit|IsDodging|IsDoor|IsEquipped|IsFactionEvil|IsFactionHidden|IsFemale|IsFlora|IsFlying|IsFood|IsFurniture|IsGameMessageBox|IsGlobalCollisionDisabled|IsHarvested|IsHiddenDoor|IsIconPathValid|IsInAir|IsIngredient|IsInOblivion|IsJumping|IsKey|IsKeyDisabled|IsKeyPressed|IsKeyPressed2|IsKeyPressed3|IsLetter|IsLight|IsLightCarriable|IsLoadDoor|IsMagicEffectCanRecover|IsMagicEffectCanRecoverC|IsMECanRecoverC|IsMECanRecover|IsMagicEffectDetrimental|IsMEDetrimental|IsMagicEffectDetrimentalC|IsMEDetrimentalC|IsMagicEffectForEnchanting|IsMagicEffectForEnchantingC|IsMEForEnchanting|IsMEForEnchantingC|IsMagicEffectForSpellmaking|IsMagicEffectForSpellmakingC|IsMEForSpellmaking|IsMEForSpellmakingC|IsMagicEffectHostile|IsMEHostile|IsMagicEffectHostileC|IsMEHostileC|IsMagicEffectMagnitudePercent|IsMagicEffectMagnitudePercentC|IsMEMagnitudePercentC|IsMEMagnitudePercent|IsMagicEffectOnSelfAllowed|IsMagicEffectOnSelfAllowedC|IsMEOnSelfAllowed|IsMEOnSelfAllowedC|IsMagicEffectOnTargetAllowed|IsMEOnTargetAllowed|IsMagicEffectOnTargetAllowedC|IsMEOnTargetAllowedC|IsMagicEffectOnTouchAllowed|IsMEOnTouchAllowed|IsMagicEffectOnTouchAllowedC|IsMEOnTouchAllowedC|IsMagicItemAutoCalc|IsMapMarkerVisible|IsMinimalUseDoor|IsModelPathValid|IsModLoaded|IsMovingBackward|IsMovingForward|IsMovingLeft|IsMovingRight|IsNthActiveEffectApplied|IsNthEffectItemScripted|IsNthEffectItemScriptHostile|IsNthEISHostile|IsOblivionGate|IsOblivionInterior|IsOblivionWorld|IsOffLimits|IsOnGround|IsPathNodeDisabled|IsPCLevelOffset|IsPersistent|IsPlayable|IsPlayable2|IsPluginInstalled|IsPoison|IsPowerAttacking|IsPrintable|IsPunctuation|IsQuestCompleted|IsQuestItem|IsRaceBonusSkill|IsRaceBonusSkillC|IsRacePlayable|IsRecoiling|IsRefDeleted|IsReference|IsRefEssential|IsScripted|IsSigilStone|IsSoulGem|IsSpellHostile|IsStaggered|IsSummonable|IsTaken|IsTextInputInUse|IsThirdPerson|IsTurningLeft|IsTurningRight|IsUnderWater|IsUppercase|IsWeapon|LeftShift|Let|LinkToDoor|LoadGameEx|Log|Log10|LogicalAnd|LogicalNot|LogicalOr|LogicalXor|MagicEffectCodeFromChars|MagicEffectFromChars|MagicEffectFromCode|MagicEffectFXPersists|MagicEffectFXPersistsC|MagicEffectHasNoArea|MEHasNoArea|MagicEffectHasNoAreaC|MEHasNoAreaC|MagicEffectHasNoDuration|MEHasNoDuration|MagicEffectHasNoDurationC|MEHasNoDurationC|MagicEffectHasNoHitEffect|MagicEffectHasNoHitEffectC|MEHasNoHitEffect|MEHasNoHitEffectC|MagicEffectHasNoIngredient|MagicEffectHasNoIngredientC|MEHasNoIngredient|MEHasNoIngredientC|MagicEffectHasNoMagnitude|MEHasNoMagnitude|MagicEffectHasNoMagnitudeC|MEHasNoMagnitudeC|MagicEffectUsesArmor|MagicEffectUsesArmorC|MagicEffectUsesAttribute|MagicEffectUsesAttributeC|MagicEffectUsesCreature|MagicEffectUsesCreatureC|MagicEffectUsesOtherActorValue|MagicEffectUsesOtherActorValueC|MEUsesOtherActorValue|MEUsesOtherActorValueC|MagicEffectUsesSkill|MagicEffectUsesSkillC|MagicEffectUsesWeapon|MagicEffectUsesWeaponC|MEUsesWeapon|MEUsesWeaponC|MagicItemHasEffect|MagicHasEffect|MagicItemHasEffectCode|MagicHasEffectC|MagicItemHasEffectCount|MagicItemHasEffectCountCode|MagicItemHasEffectCountC|MagicItemHasEffectItemScript|MatchPotion|MatrixAdd|MatAdd|MatrixDeterminant|det|MatrixInvert|MatInv|MatrixMultiply|MatMult|MatrixRREF|RREF|MatrixScale|MatScale|MatrixSubtract|MatSubtract|MatrixTrace|tr|MatrixTranspose|Transpose|MenuHoldKey|MenuReleaseKey|MenuTapKey|MessageBoxEx|MessageEx|ModActorValue2|ModAV2|ModActorValueC|ModAVC|ModArmorAR|ModAttackDamage|ModAVMod|ModAVModC|ModCurrentCharge|ModEnchantmentCharge|ModEnchantmentCost|ModEquippedCurrentCharge|ModEquippedCurrentHealth|ModFemaleBipedPath|ModFemaleGroundPath|ModFemaleIconPath|ModGoldValue|ModIconPath|ModLocalDataExists|ModMaleBipedPath|ModMaleGroundPath|ModMaleIconPath|ModModelPath|ModName|ModNthActiveEffectMagnitude|ModNthAEMagnitude|ModNthEffectItemArea|ModNthEIArea|ModNthEffectItemDuration|ModNthEIDuration|ModNthEffectItemMagnitude|ModNthEIMagnitude|ModNthEffectItemScriptName|ModNthEISName|ModObjectCharge|ModObjectHealth|ModPCMovementSpeed|ModPCSpellEffectiveness|ModPlayerSkillExp|ModPlayerSkillExpC|ModQuality|ModSigilStoneUses|ModSpellMagickaCost|ModWeaponReach|ModWeaponSpeed|ModWeight|MoveMouseX|MoveMouseY|MoveTextInputCursor|NameIncludes|NumToHex|OffersApparatus|OffersArmor|OffersBooks|OffersClothing|OffersIngredients|OffersLights|OffersMagicItems|OffersMiscItems|OffersPotions|OffersRecharging|OffersRepair|OffersServicesC|OffersSpells|OffersTraining|OffersWeapons|OnControlDown|OnKeyDown|OpenTextInput|OutputLocalMapPicturesOverride|ParentCellHasWater|HasWater|PathEdgeExists|PlayIdle|Pow|Print|PrintActiveTileInfo|PrintD|PrintTileInfo|PrintToConsole|PrintC|QuestExists|Rand|Rcos|RefreshCurrentClimate|ReleaseKey|RemoveAllEffectItems|RemoveBaseSpell|RemoveEnchantment|RemoveEquippedWeaponPoison|RemoveEventHandler|RemoveFromLeveledList|RemoveItemNS|RemoveLevItemByLevel|RemoveMeIR|RemoveModLocalData|RemoveNthEffectItem|RemoveNthEffect|RemoveNthLevItem|RemoveNthMagicEffectCounter|RemoveNthMagicEffectCounterC|RemoveScript|RemoveSpellNS|ResetAllVariables|ResolveModIndex|RightShift|Rsin|RunBatchScript|RunScriptLine|IsFormValid|SetActiveQuest|SetActorRespawns|SetActorValueC|SetAVC|SetAltControl|SetApparatusType|SetArmorAR|SetArmorType|SetArrowProjectileBowEnchantment|SetArrowProjectileEnchantment|SetArrowProjectilePoison|SetAttackDamage|SetAVMod|SetAVModC|SetBaseForm|SetBipedIconPathEX|SetBipedModelPathEX|SetBipedSlotMask|SetBookCantBeTaken|SetBookIsScroll|SetBookSkillTaught|SetButtonPressed|SetCanCastPower|SetCanCorpseCheck|SetCanFastTravelFromWorld|SetCanTravelToMapMarker|SetCellBehavesAsExterior|SetCellClimate|SetCellHasWater|SetCellIsPublic|SetCellLighting|SetCellResetHours|SetCellWaterHeight|SetCellWaterType|SetChanceNone|SetClassAttribute|SetClassAttributeC|SetClassSkills|SetClassSkills2|SetClassSpecialization|SetClimateHasMasser|SetClimateHasSecunda|SetClimateMoonPhaseLength|SetClimateSunriseBegin|SetClimateSunriseEnd|SetClimateSunsetBegin|SetClimateSunsetEnd|SetClimateVolatility|SetCloseSound|SetCombatStyleAcrobaticsDodgeChance|SetCombatStyleAttackChance|SetCombatStyleAttackDuringBlockMult|SetCombatStyleAttackNotUnderAttackMult|SetCombatStyleAttackSkillModBase|SetCombatStyleAttackSkillModMult|SetCombatStyleAttackUnderAttackMult|SetCombatStyleBlockChance|SetCombatStyleBlockNotUnderAttackMult|SetCombatStyleBlockSkillModBase|SetCombatStyleBlockSkillModMult|SetCombatStyleBlockUnderAttackMult|SetCombatStyleBuffStandoffDist|SetCombatStyleDodgeBackNotUnderAttackMult|SetCombatStyleDodgeBackTimerMax|SetCombatStyleDodgeBackTimerMin|SetCombatStyleDodgeBackUnderAttackMult|SetCombatStyleDodgeChance|SetCombatStyleDodgeFatigueModBase|SetCombatStyleDodgeFatigueModMult|SetCombatStyleDodgeFWAttackingMult|SetCombatStyleDodgeFWNotAttackingMult|SetCombatStyleDodgeFWTimerMax|SetCombatStyleDodgeFWTimerMin|SetCombatStyleDodgeLRChance|SetCombatStyleDodgeLRTimerMax|SetCombatStyleDodgeLRTimerMin|SetCombatStyleDodgeNotUnderAttackMult|SetCombatStyleDodgeUnderAttackMult|SetCombatStyleEncumberedSpeedModBase|SetCombatStyleEncumberedSpeedModMult|SetCombatStyleFleeingDisabled|SetCombatStyleGroupStandoffDist|SetCombatStyleH2HBonusToAttack|SetCombatStyleHoldTimerMax|SetCombatStyleHoldTimerMin|SetCombatStyleIdleTimerMax|SetCombatStyleIdleTimerMin|SetCombatStyleIgnoreAlliesInArea|SetCombatStyleKOBonusToAttack|SetCombatStyleKOBonusToPowerAttack|SetCombatStyleMeleeAlertOK|SetCombatStylePowerAttackChance|SetCombatStylePowerAttackFatigueModBase|SetCombatStylePowerAttackFatigueModMult|SetCombatStylePrefersRanged|SetCombatStyleRangedStandoffDist|SetCombatStyleRangeMaxMult|SetCombatStyleRangeOptimalMult|SetCombatStyleRejectsYields|SetCombatStyleRushAttackChance|SetCombatStyleRushAttackDistMult|SetCombatStyleStaggerBonusToAttack|SetCombatStyleStaggerBonusToPowerAttack|SetCombatStyleSwitchDistMelee|SetCombatStyleSwitchDistRanged|SetCombatStyleWillYield|SetContainerRespawns|SetUnsafeContainer|SetControl|SetCreatureSkill|SetCreatureSoundBase|SetCurrentCharge|SetCurrentHealth|SetCurrentSoulLevel|SetDebugMode|SetDescription|SetDetectionState|SetDisableGlobalCollision|SetDoorTeleport|SetEnchantment|SetEnchantmentCharge|SetEnchantmentCost|SetEnchantmentType|SetEquipmentSlot|SetEquippedCurrentCharge|SetEquippedCurrentHealth|SetEquippedWeaponPoison|SetEventHandler|SetEyes|SetFactionEvil|SetFactionHidden|SetFactionSpecialCombat|SetFemale|SetFemaleBipedPath|SetFemaleGroundPath|SetFemaleIconPath|SetFunctionValue|SetGameDifficulty|SetGoldValue|SetGoldValueT|SetHair|SetHarvested|SetHasBeenPickedUp|SetTaken|SetHidesAmulet|SetHidesRings|SetHotkeyItem|SetIconPath|SetIgnoresResistance|SetIngredient|SetIngredientChance|SetInputText|SetIsAutomaticDoor|SetIsControl|SetIsFood|SetIsHiddenDoor|SetIsMinimalUseDoor|SetIsOblivionGate|SetIsPlayable|SetLightDuration|SetLightRadius|SetLightRGB|SetLocalGravity|SetLocalGravityVector|SetLoopSound|SetLowLevelProcessing|SetMagicEffectAreaSound|SetMagicEffectAreaSoundC|SetMagicEffectBarterFactor|SetMagicEffectBarterFactorC|SetMagicEffectBaseCost|SetMagicEffectBaseCostC|SetMagicEffectBoltSound|SetMagicEffectBoltSoundC|SetMagicEffectCanRecover|SetMagicEffectCanRecoverC|SetMagicEffectCastingSound|SetMagicEffectCastingSoundC|SetMagicEffectCounters|SetMagicEffectCountersC|SetMagicEffectEnchantFactor|SetMagicEffectEnchantFactorC|SetMagicEffectEnchantShader|SetMagicEffectEnchantShaderC|SetMagicEffectForEnchanting|SetMagicEffectForEnchantingC|SetMagicEffectForSpellmaking|SetMagicEffectForSpellmakingC|SetMagicEffectFXPersists|SetMagicEffectFXPersistsC|SetMagicEffectHitShader|SetMagicEffectHitShaderC|SetMagicEffectHitSound|SetMagicEffectHitSoundC|SetMagicEffectIcon|SetMagicEffectIconC|SetMagicEffectIsDetrimental|SetMagicEffectIsDetrimentalC|SetMagicEffectIsHostile|SetMagicEffectIsHostileC|SetMagicEffectLight|SetMagicEffectLightC|SetMagicEffectMagnitudePercent|SetMagicEffectMagnitudePercentC|SetMagicEffectModel|SetMagicEffectModelC|SetMagicEffectName|SetMagicEffectNameC|SetMagicEffectNoArea|SetMagicEffectNoAreaC|SetMagicEffectNoDuration|SetMagicEffectNoDurationC|SetMagicEffectNoHitEffect|SetMagicEffectNoHitEffectC|SetMagicEffectNoIngredient|SetMagicEffectNoIngredientC|SetMagicEffectNoMagnitude|SetMagicEffectNoMagnitudeC|SetMagicEffectOnSelfAllowed|SetMagicEffectOnSelfAllowedC|SetMagicEffectOnTargetAllowed|SetMagicEffectOnTargetAllowedC|SetMagicEffectOnTouchAllowed|SetMagicEffectOnTouchAllowedC|SetMagicEffectOtherActorValue|SetMagicEffectOtherActorValueC|SetMagicEffectProjectileSpeed|SetMagicEffectProjectileSpeedC|SetMagicEffectResistValue|SetMagicEffectResistValueC|SetMagicEffectSchool|SetMagicEffectSchoolC|SetMagicEffectUsedObject|SetMagicEffectUsedObjectC|SetMagicEffectUsesActorValue|SetMagicEffectUsesActorValueC|SetMagicEffectUsesArmor|SetMagicEffectUsesArmorC|MEUsesArmor|MEUsesArmorC|SetMagicEffectUsesAttribute|SetMagicEffectUsesAttributeC|MEUsesAttribute|MEUsesAttributeC|SetMagicEffectUsesCreature|SetMagicEffectUsesCreatureC|MEUsesCreature|MEUsesCreatureC|SetMagicEffectUsesSkill|SetMagicEffectUsesSkillC|SetMagicEffectUsesWeapon|SetMagicEffectUsesWeaponC|SetMagicItemAutoCalc|SetMagicProjectileSpell|SetMPSpell|SetMaleBipedPath|SetMaleGroundPath|SetMaleIconPath|SetMapMarkerType|SetMapMarkerVisible|SetMenuFloatValue|SetMenuStringValue|SetMerchantContainer|SetMessageIcon|SetMessageSound|SetModelPath|SetModLocalData|SetMouseSpeedX|SetMouseSpeedY|SetName|SetNameEx|SetNoPersuasion|SetNthActiveEffectMagnitude|SetNthAEMagnitude|SetNthEffectItemActorValue|SetNthEIAV|SetNthEffectItemActorValueC|SetNthEIAVC|SetNthEffectItemArea|SetNthEIArea|SetNthEffectItemDuration|SetNthEIDuration|SetNthEffectItemMagnitude|SetNthEIMagnitude|SetNthEffectItemRange|SetNthEIRange|SetNthEffectItemScript|SetNthEIScript|SetNthEffectItemScriptHostile|SetNthEISHostile|SetNthEffectItemScriptName|SetNthEISName|SetNthEffectItemScriptNameEX|SetNthEffectItemScriptSchool|SetNthEISSchool|SetNthEffectItemScriptVisualEffect|SetNthEISVisualEffect|SetNthEffectItemScriptVisualEffectC|SetNthEISVisualEffectC|SetNthFactionRankNameEX|SetNumericGameSetting|SetNumericINISetting|SetObjectCharge|SetObjectHealth|SetOffersApparatus|SetOffersArmor|SetOffersBooks|SetOffersClothing|SetOffersIngredients|SetOffersLights|SetOffersMagicItems|SetOffersMiscItems|SetOffersPotions|SetOffersRecharging|SetOffersRepair|SetOffersServicesC|SetOffersSpells|SetOffersTraining|SetOffersWeapons|SetOLMPGrids|SetOpenKey|SetOpenSound|SetPackageAllowFalls|SetPackageAllowSwimming|SetPackageAlwaysRun|SetPackageAlwaysSneak|SetPackageArmorUnequipped|SetPackageContinueIfPCNear|SetPackageData|SetPackageDefensiveCombat|SetPackageLocationData|SetPackageLockDoorsAtEnd|SetPackageLockDoorsAtLocation|SetPackageLockDoorsAtStart|SetPackageMustComplete|SetPackageMustReachLocation|SetPackageNoIdleAnims|SetPackageOffersServices|SetPackageOncePerDay|SetPackageScheduleData|SetPackageSkipFalloutBehavior|SetPackageTarget|SetPackageTargetData|SetPackageUnlockDoorsAtEnd|SetPackageUnlockDoorsAtLocation|SetPackageUnlockDoorsAtStart|SetPackageUseHorse|SetPackageWeaponsUnequipped|SetPathNodeDisabled|SetPCAMurderer|SetPCAttributeBonus|SetPCAttributeBonusC|SetPCLevelOffset|SetPCMajorSkillUps|SetPCTrainingSessionsUsed|SetPlayerBirthsign|SetPlayerProjectile|Setplayerskeletonpath|SetPlayerSkillAdvances|SetPlayerSkillAdvancesC|SetPlayersLastRiddenHorse|SetPowerTimer|SetProjectileSource|SetProjectileSpeed|SetQuality|SetQuestItem|SetRaceAlias|SetRacePlayable|SetRaceScale|SetRaceVoice|SetRaceWeight|SetRefCount|SetRefEssential|SetScaleEX|SetScript|SetSigilStoneUses|SetSkillGoverningAttribute|SetSkillSpecialization|SetSkillUseIncrement|SetSoulGemCapacity|SetSoulLevel|SetSpellAreaEffectIgnoresLOS|SetSpellDisallowAbsorbReflect|SetSpellExplodesWithNoTarget|SetSpellHostile|SetSpellImmuneToSilence|SetSpellMagickaCost|SetSpellMasteryLevel|SetSpellPCStart|SetSpellScriptEffectAlwaysApplies|SetSpellType|SetStringGameSettingEX|SetSummonable|SetTextInputControlHandler|SetTextInputDefaultControlsDisabled|SetTexturePath|SetTimeLeft|SetTrainerLevel|SetTrainerSkill|SetTravelHorse|SetVelocity|SetVerticalVelocity|SetWeaponReach|SetWeaponSpeed|SetWeaponType|SetWeatherCloudSpeedLower|SetCloudSpeedLower|SetWeatherCloudSpeedUpper|SetCloudSpeedUpper|SetWeatherColor|SetWeatherFogDayFar|SetFogDayFar|SetWeatherFogDayNear|SetFogDayNear|SetWeatherFogNightFar|SetFogNightFar|SetWeatherFogNightNear|SetFogNightNear|SetWeatherHDRValue|SetHDRValue|SetWeatherLightningFrequency|SetLightningFrequency|SetWeatherSunDamage|SetSunDamage|SetWeatherSunGlare|SetSunGlare|SetWeatherTransDelta|SetTransDelta|SetWeatherWindSpeed|SetWindSpeed|SetWeight|Sin|dsin|rsin|Sinh|dsinh|rsinh|SquareRoot|sqrt|Sv_Compare|Sv_Construct|Sv_Count|Sv_Destruct|Sv_Erase|Sv_Find|Sv_Insert|Sv_Length|Sv_Percentify|Sv_Replace|Sv_Split|Sv_ToLower|Sv_ToNumeric|Sv_ToUpper|Tan|dtan|rtan|Tanh|dtanh|rtanh|TapControl|TapKey|TestExpr|ToggleCreatureModel|ToggleFirstPerson|ToggleSkillPerk|ToggleSpecialAnim|ToLower|ToNumber|ToString|ToUpper|TriggerPlayerSkillUse|TriggerPlayerSkillUseC|TypeOf|UncompleteQuest|UnequipItemNS|UnequipItemSilent|UnequipMe|UnHammerKey|Update3D|UpdateTextInput|VectorCross|VectorDot|dot|VectorMagnitude|VecMag|VectorNormalize|VecNorm/
  ], { prefix: '', suffix: '' });  
    
  var builtins = buildRegexp([symbolBuiltins, varBuiltins, vanillaBuiltins, obseBuiltins], { suffix: notCharacterOrDash });
    
  var wtfBuiltins = buildRegexp([
    /DeleteLinesFromLog|GetLogLineCount|GetRegisteredLogNames|ReadFromLog|RegisterLog|Scribe|UnregisterLog|NiAlphaPropertyGetBlendState|NiAlphaPropertyGetDestinationBlendFunction|NiAlphaPropertyGetSourceBlendFunction|NiAlphaPropertyGetTestFunction|NiAlphaPropertyGetTestState|NiAlphaPropertyGetTestThreshold|NiAlphaPropertyGetTriangleSortMode|NiAlphaPropertySetBlendState|NiAlphaPropertySetDestinationBlendFunction|NiAlphaPropertySetSourceBlendFunction|NiAlphaPropertySetTestFunction|NiAlphaPropertySetTestState|NiAlphaPropertySetTestThreshold|NiAlphaPropertySetTriangleSortMode|NiAVObjectAddProperty|NiAVObjectClearCollisionObject|NiAVObjectCopyCollisionObject|NiAVObjectDeleteProperty|NiAVObjectGetCollisionMode|NiAVObjectGetCollisionObject|NiAVObjectGetLocalRotation|NiAVObjectGetLocalScale|NiAVObjectGetLocalTransform|NiAVObjectGetLocalTranslation|NiAVObjectGetNumProperties|NiAVObjectGetProperties|NiAVObjectGetPropertyByType|NiAVObjectSetCollisionMode|NiAVObjectSetLocalRotation|NiAVObjectSetLocalScale|NiAVObjectSetLocalTransform|NiAVObjectSetLocalTranslation|BSFurnitureMarkerGetPositionRefs|BSFurnitureMarkerSetPositionRefs|NiExtraDataGetArray|NiExtraDataGetName|NiExtraDataGetNumber|NiExtraDataGetString|NiExtraDataSetArray|NiExtraDataSetName|NiExtraDataSetNumber|NiExtraDataSetString|GetNifTypeIndex|NiMaterialPropertyGetAmbientColor|NiMaterialPropertyGetDiffuseColor|NiMaterialPropertyGetEmissiveColor|NiMaterialPropertyGetGlossiness|NiMaterialPropertyGetSpecularColor|NiMaterialPropertyGetTransparency|NiMaterialPropertySetAmbientColor|NiMaterialPropertySetDiffuseColor|NiMaterialPropertySetEmissiveColor|NiMaterialPropertySetGlossiness|NiMaterialPropertySetSpecularColor|NiMaterialPropertySetTransparency|NifClose|NifGetNumBlocks|NifGetOriginalPath|NifGetPath|NifOpen|NifWriteToDisk|NiNodeAddChild|NiNodeCopyChild|NiNodeDeleteChild|NiNodeGetChildByName|NiNodeGetChildren|NiNodeGetNumChildren|NiObjectGetType|NiObjectGetTypeName|NiObjectNETAddExtraData|NiObjectNETDeleteExtraData|NiObjectNETGetExtraData|NiObjectNETGetExtraDataByName|NiObjectNETGetName|NiObjectNETGetNumExtraData|NiObjectNETSetName|NiObjectTypeDerivesFrom|NiSourceTextureGetFile|NiSourceTextureIsExternal|NiSourceTextureSetExternalTexture|NiStencilPropertyGetFaceDrawMode|NiStencilPropertyGetFailAction|NiStencilPropertyGetPassAction|NiStencilPropertyGetStencilFunction|NiStencilPropertyGetStencilMask|NiStencilPropertyGetStencilRef|NiStencilPropertyGetStencilState|NiStencilPropertyGetZFailAction|NiStencilPropertySetFaceDrawMode|NiStencilPropertySetFailAction|NiStencilPropertySetPassAction|NiStencilPropertySetStencilFunction|NiStencilPropertySetStencilMask|NiStencilPropertySetStencilRef|NiStencilPropertySetStencilState|NiStencilPropertySetZFailAction|NiTexturingPropertyAddTextureSource|NiTexturingPropertyDeleteTextureSource|NiTexturingPropertyGetTextureCenterOffset|NiTexturingPropertyGetTextureClampMode|NiTexturingPropertyGetTextureCount|NiTexturingPropertyGetTextureFilterMode|NiTexturingPropertyGetTextureFlags|NiTexturingPropertyGetTextureRotation|NiTexturingPropertyGetTextureSource|NiTexturingPropertyGetTextureTiling|NiTexturingPropertyGetTextureTranslation|NiTexturingPropertyGetTextureUVSet|NiTexturingPropertyHasTexture|NiTexturingPropertySetTextureCenterOffset|NiTexturingPropertySetTextureClampMode|NiTexturingPropertySetTextureCount|NiTexturingPropertySetTextureFilterMode|NiTexturingPropertySetTextureFlags|NiTexturingPropertySetTextureRotation|NiTexturingPropertySetTextureTiling|NiTexturingPropertySetTextureTranslation|NiTexturingPropertySetTextureUVSet|NiTexturingPropertyTextureHasTransform|NiVertexColorPropertyGetLightingMode|NiVertexColorPropertyGetVertexMode|NiVertexColorPropertySetVertexMode|NiVertexColorPropertySetLightingMode|ArrayCmp|ArrayCount|ArrayEsp|ArrayProtect|ArraySize|AutoSclHudS|AutoSclHudT|CopyArray|CopyString|CreateArray|CreateString|Csc|DelAllHudSs|DelAllHudTs|DelFile|DelHudS|DelHudT|DelTxtFile|DestroyAllArrays|DestroyAllStrings|DestroyArray|DestroyString|DupArray|EspToString|FileToString|FindFirstFile|FindFloatInArray|FindInArray|FindNextFile|FindRefInArray|FirstFreeInArray|FirstInArray|FloatToString|GetEsp|GetFileSize|GetInArray|GetRefEsp|GetTypeInArray|IniDelKey|IniKeyExists|IniReadFloat|IniReadInt|IniReadRef|IniReadString|IniWriteFloat|IniWriteInt|IniWriteRef|IniWriteString|IntToHex|IntToString|IsHudEnabled|IsPluggyDataReset|LC|ModRefEsp|NewHudS|NewHudT|PackArray|Rcsc|RefToString|RemInArray|RenFile|RenTxtFile|ScreenInfo|SetFloatInArray|SetHudT|SetInArray|SetRefInArray|SetString|StringCat|StringCmp|StringEsp|StringGetName|StringIns|StringLen|StringMsg|StringMsgBox|StringPos|StringProtect|StringRep|StringSetName|StringToFloat|StringToInt|StringToRef|StringToTxtFile|StrLC|ToOBSE|TxtFileExists|SetBodyAssetOverride|GetBodyAssetOverride|ResetBodyAssetOverride|SetHeadAssetOverride|GetHeadAssetOverride|ResetHeadAssetOverride|GetFaceGenAge|SetFaceGenAge|RefreshAnimData|SetAgeTextureOverride|ResetAgeTextureOverride|ToggleAnimOverride|RegisterEquipmentOverrideHandler|UnregisterEquipmentOverrideHandler|tile_GetFloat|tile_GetString|tile_SetFloat|tile_SetString|tile_GetInfo|tile_GetName|InsertXML|InsertXMLTemplate|IsTextEditInUse|GetTextEditBox|GetTextEditString|SetTextEditString|ShowMagicPopupMenu|ShowLevelUpMenu|ShowTrainingMenu|GetTrainingMenuSkill|GetTrainingMenuLevel|GetTrainingMenuCost|ShowTextEditMenu|ShowGenericMenu|GetGenericButtonPressed|mqGetCurrentQuests|mqGetCompletedQuests|mqGetQuestCompleted|mqUncompleteQuest|mqGetActiveQuest|mqSetActiveQuest|mqGetActiveQuestTargets|GetRequiredSkillExpC|GetSkillSpecializationC|SetSkillSpecializationC|SetTrainerSkillC|GetSkillCode|GetSkillForm|GetAllSkills|GetFontLoaded|GetLoadedFonts|GetWorldMapData|SetWorldMapData|GetWorldMapDoor|GetMousePos|GetMouseImage|SetMouseImage|OnOpen|OnClose|OnClick|OnMouseover|SetMenuEventHandler|RemoveMenuEventHandler|GetMenuEventType|DumpAVC|DumpAVF|GetAVModC|GetAVModF|ModAVModC|ModAVModF|SetAVModC|SetAVModF|GetAVBaseCalcC|GetAVBaseCalcF|GetAVMaxC|GetAVMaxF|GetAVCurrentC|GetAVCurrent/
  ], { suffix: notCharacterOrDash });  
    
  var staticBuiltins = buildRegexp([
    /Function|GameMode|MenuMode|OnActivate|OnActorEquip|OnActorUnequip|OnAdd|OnAlarm|OnAlarmVictim|OnDeath|OnDrop|OnEquip|OnHit|OnHitWith|OnKnockout|OnLoad|OnMagicEffectHit|OnMurder|OnPackageChange|OnPackageDone|OnPackageStart|OnReset|OnSell|OnStartCombat|OnTrigger|OnTriggerActor|OnTriggerMob|OnUnequip|ScriptEffectStart|ScriptEffectFinish|ScriptEffectUpdate|OnHit|OnHitWith|OnMagicEffectHit|OnMagicEffectHit2|OnActorEquip|OnDeath|OnMurder|OnKnockout|OnActorUnequip|OnAlarmTrespass|OnPackageChange|OnPackageStart|OnPackageDone|OnStartCombat|OnActivate|OnVampireFeed|OnSkillUp|OnScriptedSkillUp|OnDrinkPotion|OnEatIngredient|OnActorDrop|OnSpellCast|OnScrollCast|OnFallImpact|OnMapMarkerAdd|OnHealthDamage|OnCreateSpell|OnCreatePotion|OnEnchant|OnAttack|OnBowAttack|OnRelease|OnBlock|OnRecoil|OnStagger|OnDodge|OnSoulTrap|OnQuestComplete|OnMagicCast|OnMagicApply|OnWaterDive|OnWaterSurface|LoadGame|SaveGame|PostLoadGame|ExitGame|ExitToMainMenu|QQQ|OnNewGame|OnSaveIni/
  ], { prefix: '', suffix: '' });     
    
  var grammar = {
    keyword: keywords,
    number: numbers,
    property: wtfBuiltins,
    header: staticBuiltins,
    operator: operators,
    builtin: builtins, 
    punctuation: punctuation,
    identifier: identifiers
    
  };

  // tokenizers
  function tokenBase(stream, state) {
    // Handle Comments
    //var ch = stream.peek();

    var parent = state.returnStack[state.returnStack.length - 1];
    if (parent && parent.shouldReturnFrom(state)) {
      state.tokenize = parent.tokenize;
      state.returnStack.pop();
      return state.tokenize(stream, state);
    }

    if (stream.eatSpace()) {
      return null;
    }

    if (stream.eat('(')) {
      state.bracketNesting += 1;
      return 'punctuation';
    }

    if (stream.eat(')')) {
      state.bracketNesting -= 1;
      return 'punctuation';
    }

    for (var key in grammar) {
      if (stream.match(grammar[key])) {
        return key;
      }
    }

    var ch = stream.next();

    // single-quote string
    if (ch === "'") {
      return tokenSingleQuoteString(stream, state);
    }

    if (ch === '$') {
      return tokenVariable(stream, state);
    }

    // double-quote string
    if (ch === '"') {
      return tokenDoubleQuoteString(stream, state);
    }

    if (ch === '<' && stream.eat(';')) {
      state.tokenize = tokenComment;
      return tokenComment(stream, state);
    }

    if (ch === ';') {
      stream.skipToEnd();
      return 'comment';
    }

    if (ch === '@') {
      var quoteMatch = stream.eat(/["']/);
      if (quoteMatch && stream.eol()) {
        state.tokenize = tokenMultiString;
        state.startQuote = quoteMatch[0];
        return tokenMultiString(stream, state);
      } else if (stream.eol()) {
        return 'error';
      } else if (stream.peek().match(/[({]/)) {
        return 'punctuation';
      } else if (stream.peek().match(varNames)) {
        // splatted variable
        return tokenVariable(stream, state);
      }
    }
    return 'error';
  }

  function tokenSingleQuoteString(stream, state) {
    var ch;
    while ((ch = stream.peek()) != null) {
      stream.next();

      if (ch === "'" && !stream.eat("'")) {
        state.tokenize = tokenBase;
        return 'string';
      }
    }

    return 'error';
  }

  function tokenDoubleQuoteString(stream, state) {
    var ch;
    while ((ch = stream.peek()) != null) {
      if (ch === '$') {
        state.tokenize = tokenStringInterpolation;
        return 'string';
      }

      stream.next();
      if (ch === '`') {
        stream.next();
        continue;
      }

      if (ch === '"' && !stream.eat('"')) {
        state.tokenize = tokenBase;
        return 'string';
      }
    }

    return 'error';
  }

  function tokenStringInterpolation(stream, state) {
    return tokenInterpolation(stream, state, tokenDoubleQuoteString);
  }

  function tokenMultiStringReturn(stream, state) {
    state.tokenize = tokenMultiString;
    state.startQuote = '"'
    return tokenMultiString(stream, state);
  }

  function tokenHereStringInterpolation(stream, state) {
    return tokenInterpolation(stream, state, tokenMultiStringReturn);
  }

  function tokenInterpolation(stream, state, parentTokenize) {
    if (stream.match('$(')) {
      var savedBracketNesting = state.bracketNesting;
      state.returnStack.push({
        /*jshint loopfunc:true */
        shouldReturnFrom: function(state) {
          return state.bracketNesting === savedBracketNesting;
        },
        tokenize: parentTokenize
      });
      state.tokenize = tokenBase;
      state.bracketNesting += 1;
      return 'punctuation';
    } else {
      stream.next();
      state.returnStack.push({
        shouldReturnFrom: function() { return true; },
        tokenize: parentTokenize
      });
      state.tokenize = tokenVariable;
      return state.tokenize(stream, state);
    }
  }

  function tokenComment(stream, state) {
    var maybeEnd = false, ch;
    while ((ch = stream.next()) != null) {
      if (maybeEnd && ch == '>') {
          state.tokenize = tokenBase;
          break;
      }
      maybeEnd = (ch === ';');
    }
    return 'comment';
  }

  function tokenVariable(stream, state) {
    var ch = stream.peek();
    if (stream.eat('{')) {
      state.tokenize = tokenVariableWithBraces;
      return tokenVariableWithBraces(stream, state);
    } else if (ch != undefined && ch.match(varNames)) {
      stream.eatWhile(varNames);
      state.tokenize = tokenBase;
      return 'variable-2';
    } else {
      state.tokenize = tokenBase;
      return 'error';
    }
  }

  function tokenVariableWithBraces(stream, state) {
    var ch;
    while ((ch = stream.next()) != null) {
      if (ch === '}') {
        state.tokenize = tokenBase;
        break;
      }
    }
    return 'variable-2';
  }

  function tokenMultiString(stream, state) {
    var quote = state.startQuote;
    if (stream.sol() && stream.match(new RegExp(quote + '@'))) {
      state.tokenize = tokenBase;
    }
    else if (quote === '"') {
      while (!stream.eol()) {
        var ch = stream.peek();
        if (ch === '$') {
          state.tokenize = tokenHereStringInterpolation;
          return 'string';
        }

        stream.next();
        if (ch === '`') {
          stream.next();
        }
      }
    }
    else {
      stream.skipToEnd();
    }

    return 'string';
  }

  var external = {
    startState: function() {
      return {
        returnStack: [],
        bracketNesting: 0,
        tokenize: tokenBase
      };
    },

    token: function(stream, state) {
      return state.tokenize(stream, state);
    },

    blockCommentStart: '<#',
    blockCommentEnd: '#>',
    lineComment: ';',
    fold: 'brace'
  };
  return external;
});

CodeMirror.defineMIME('text/x-tesscript', 'tesscript');
});
